### PR TITLE
feature: Add symfony standard

### PR DESCRIPTION
**Pull request by ruiteix**

### CODE REVIEW

**Comment by ruiteix** [comment]
@josemiguelmelo  Thank you for your feedback !
Everything's been fixed ;)

**Comment by josemiguelmelo** [comment]
@ruiteix Thank you, it seems to be fine now!

I would like to ask if you could just amend the commit to trigger the CI 🙂

**Comment by ruiteix** [comment]
Ok done

**Comment by lolgab** [comment]
You only miss `scalafmt` now.
try:
```bash
sbt scalafmt test:scalafmt sbt:scalafmt
```

**Comment by josemiguelmelo** [comment]
LGTM 👍 
Thanks for your contribution! 🎉

**Pull request merged**
